# Generated by Django 5.2.3 on 2026-02-14 08:07

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_customuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='avatar/'),
        ),
    ]
